import type { Json } from "atom.io/foundations/json"

/** The wire protocol version implemented by this release of Mosaic. */
export const MOSAIC_PROTOCOL_VERSION = 1 as const

/** Stable transport event names shared by every Mosaic resource. */
export const MOSAIC_EVENTS = {
	join: `atom.io:mosaic:join`,
	operation: `atom.io:mosaic:operation`,
	presence: `atom.io:mosaic:presence`,
	rejection: `atom.io:mosaic:rejection`,
	snapshot: `atom.io:mosaic:snapshot`,
} as const

export type MosaicProtocolVersion = typeof MOSAIC_PROTOCOL_VERSION

export type MosaicModelIdentifier = {
	readonly key: string
	readonly version: number
}

export type MosaicResourceIdentifier = {
	readonly key: string
	readonly model: MosaicModelIdentifier
}

/** Metadata generated by one logical client session. */
export type MosaicProposalMetadata = {
	readonly dependencies: readonly string[]
	readonly group: string | null
	readonly id: string
	readonly session: string
}

/** Untrusted operation proposed by a client. Authorship is server-stamped. */
export type MosaicOperationProposal<
	Operation extends Json.Serializable = Json.Serializable,
> = MosaicProposalMetadata & {
	readonly model: MosaicModelIdentifier
	readonly operation: Operation
	readonly protocolVersion: MosaicProtocolVersion
	readonly resource: string
}

/** An operation whose actor has been authenticated by the server. */
export type MosaicOperationEnvelope<
	Operation extends Json.Serializable = Json.Serializable,
> = MosaicOperationProposal<Operation> & {
	readonly actor: string
}

export type MosaicOperationMetadata = MosaicProposalMetadata & {
	readonly actor: string
}

/** A durable checkpoint used for hydration and revision-gap recovery. */
export type MosaicSnapshotEnvelope<
	Snapshot extends Json.Serializable = Json.Serializable,
> = {
	/** The subset of the joining client's pending IDs already accepted. */
	readonly acceptedPendingOperationIds: readonly string[]
	readonly model: MosaicModelIdentifier
	readonly protocolVersion: MosaicProtocolVersion
	readonly resource: string
	readonly revision: number
	/** Correlates the snapshot with the currently active client incarnation. */
	readonly session: string
	readonly snapshot: Snapshot
}

/** Request to join or resynchronize one resource stream. */
export type MosaicJoinEnvelope = {
	readonly knownRevision: number | null
	readonly model: MosaicModelIdentifier
	readonly pendingOperationIds: readonly string[]
	readonly protocolVersion: MosaicProtocolVersion
	readonly resource: string
	readonly session: string
}

/** An accepted operation paired with its server-assigned stream revision. */
export type MosaicAcceptedOperationEnvelope<
	Operation extends Json.Serializable = Json.Serializable,
> = {
	readonly operation: MosaicOperationEnvelope<Operation>
	readonly revision: number
}

export type MosaicRejectionCode =
	| `capacity-exceeded`
	| `incompatible-version`
	| `invalid-model-operation`
	| `invalid-payload`
	| `missing-dependency`
	| `operation-id-collision`
	| `resource-unavailable`
	| `stale-history`
	| `unauthorized`

export type MosaicRecovery =
	| `discard-operation`
	| `none`
	| `resnapshot`
	| `retry`
	| `upgrade`

/** A safe, structured rejection of an operation or resource request. */
export type MosaicRejectionEnvelope = {
	readonly code: MosaicRejectionCode
	readonly operationId: string | null
	readonly protocolVersion: MosaicProtocolVersion
	readonly reason: string
	readonly recovery: MosaicRecovery
	readonly resource: string
	/** Correlates join- and operation-level failures with one client incarnation. */
	readonly session: string
}

/** Untrusted ephemeral presence proposed by a bound client session. */
export type MosaicPresenceProposal<
	Presence extends Json.Serializable = Json.Serializable,
> = {
	readonly presence: Presence
	readonly protocolVersion: MosaicProtocolVersion
	readonly resource: string
	readonly session: string
}

/** Ephemeral presence stamped with the authenticated actor. */
export type MosaicPresenceEnvelope<
	Presence extends Json.Serializable = Json.Serializable,
> = MosaicPresenceProposal<Presence> & {
	readonly actor: string
}
