[tools]
bun = "1.4.0"
"github:Boeing/config-file-validator" = "2.3.0"
hk = "1.56.1"
ni = "30.5.0"
node = "26.8.1"
pnpm = "11.24.0"
ripgrep = "15.2.0"

[tools."asdf:mise-plugins/mise-postgres"]
version = "18.4"

[tools."asdf:mise-plugins/mise-postgres".install_env]
POSTGRES_CONFIGURE_OPTIONS = "--with-openssl --with-zlib --with-uuid=e2fs --without-icu"
POSTGRES_SKIP_INITDB = "1"

[env]
HK_MISE = "1"
