blockExoticSubdeps: true
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - atom.io
  - break-check
  - comline
  - lasertag
  - recoverage
  - takua
  - treetrunks
autoInstallPeers: false
verifyDepsBeforeRun: error

packages:
  - "apps/*"
  - "packages/*"
  - "templates/*"

allowBuilds:
  "@vscode/vsce-sign": true
  dprint: true
  "esbuild": true
  keytar: true
  "rolldown": true
  "sharp": true
  simple-git-hooks: false
  "unrs-resolver": true
  "workerd": true
