name: Coverage

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_API: ${{ secrets.TURBO_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID }}

defaults:
  run:
    shell: bash

jobs:
  Total:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    env:
      ATOM_IO_TEST_POSTGRES_SKIP_MISE: "true"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        with:
          postgres-version: "18"
          port: "59432"
      - run: git rev-parse HEAD > git.sha
      - run: pnpm cov:up
        env:
          RECOVERAGE_CLOUD_TOKEN: ${{ secrets.RECOVERAGE_CLOUD_TOKEN }}

  Public:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    env:
      ATOM_IO_TEST_POSTGRES_SKIP_MISE: "true"
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        with:
          postgres-version: "18"
          port: "59432"
      - run: pnpm cov:pub
