name: Lint

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "mosaic-domains"]
    types: [edited, opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_API: ${{ secrets.TURBO_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID }}

defaults:
  run:
    shell: bash

jobs:
  Dprint:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: node pnpm
      - run: pnpm fmt:check

  Dependencies:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: node pnpm
      - run: pnpm lint:deps

  ESLint:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm lint:eslint

  JSONSchemas:
    name: JSON Schemas
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: ./.github/actions/setup
        with:
          packages: github:Boeing/config-file-validator node pnpm
      - run: validator .

  Lasertag:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm lint:lasertag

  Oxlint:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm lint:oxlint

  Tonnage:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm run tonnage:check

  Types:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm lint:types
