name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "mosaic-domains"]
    types: [edited, opened, reopened, synchronize]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TURBO_API: ${{ secrets.TURBO_API }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAMID: ${{ vars.TURBO_TEAMID }}

defaults:
  run:
    shell: bash

jobs:
  Vitest:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    env:
      ATOM_IO_TEST_POSTGRES_SKIP_MISE: "true"
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        with:
          postgres-version: "18"
          port: "59432"
      - run: pnpm run test

  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm run build
      - run: pnpm run bundle:size:test

  Manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - run: pnpm run manifest:test

  BreakCheck:
    name: Break Check
    runs-on: ubuntu-latest
    timeout-minutes: 9
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup
        with:
          packages: bun node pnpm
      - uses: ikalnytskyi/action-setup-postgres@c4dda34aae1c821e3a771b68b73b13af3198a7ee # v8
        with:
          postgres-version: "18"
          port: "59432"
      - run: pnpm test:breaks
